KCL-6857 Move configuration UI to new design
Kentico/kontent-sample-app-net pull request #123
Opened 2021-05-25 07:30 UTC by jankalfus

Moved configuration UI to new design + did some code cleanup

2021-05-26 10:42 UTC, Simply007 commented
The CI probably fails because the pull request originated in different repository:
* https://github.com/PowerShell/PowerShell/issues/5911

2021-05-26 13:25 UTC, PetrSvirak requested changes
Thanks. The code looks mostly good to me. There few minor things to handle here or there. You plan some rebasing, so I will have yet another look at this PR afterward for sure.

2021-05-26 13:43 UTC, jankalfus commented on DancingGoat/Areas/Admin/Views/Shared/_MessagesPartial.cshtml
> +    if (ViewBag.Message != null)
Actually, this fixes a bug. The code exploded whenever it got to this point and the `Message` wasn't null. `ViewBag.Message` is of dynamic type, but in fact, it's set to an instance of `MessageModel`, not a `string`, hence can't be used as such, hence the explosion 😀

2021-05-26 13:46 UTC, jankalfus commented on DancingGoat/wwwroot/css/UserMessage.less
> +}
Good point, I'll remove it.

2021-05-26 13:48 UTC, jankalfus commented on DancingGoat/wwwroot/css/admin/UserMessage.less
> +  white-space: nowrap; /* added line */
I don't either 😀 I'll remove it.

2021-05-26 13:55 UTC, jankalfus commented on DancingGoat/wwwroot/css/admin/UserMessage.less
> +    filter: invert(100%) invert(8%) sepia(100%) saturate(7451%) hue-rotate(2deg) brightness(91%) contrast(108%);
There's a single image in _MessagesPartial.cshtml, and that file is used in both the admin part and dancing goat itself. What I guess we could do is have a div with background set to this image and then set the background in each respective less file. I'll check it out.

2021-05-26 13:59 UTC, jankalfus commented on DancingGoat/Areas/Admin/Views/SelfConfig/Index.cshtml
> +@{ await Html.RenderPartialAsync("~/Areas/Admin/Views/Shared/_MessagesPartial.cshtml"); }
I don't have access :(

2021-05-26 14:12 UTC, jankalfus commented on DancingGoat/Areas/Admin/Views/SelfConfig/Index.cshtml
> +@{ await Html.RenderPartialAsync("~/Areas/Admin/Views/Shared/_MessagesPartial.cshtml"); }
https://github.com/Kentico/kontent-sample-app-net/pull/125

2021-05-27 07:00 UTC, PetrSvirak commented on DancingGoat/Areas/Admin/Views/Shared/_MessagesPartial.cshtml
> +    if (ViewBag.Message != null)
Lovely. You know the proverb: "Dynamic is the JavaScript of C#" 🤣

2021-05-27 07:30 UTC, PetrSvirak commented on DancingGoat/wwwroot/css/.gitignore
> +*.css
Sorted out in https://github.com/Kentico/kontent-sample-app-net/pull/126

2021-05-27 07:43 UTC, PetrSvirak commented on DancingGoat/wwwroot/css/admin/layout.less
> +  .col + .col {
I would hope Safari adoption sky-rockets with every release (in my imagination, mac update managers break in small tents in the queue in front of the servers, waiting for an official release for hours and days 👼), but I guess some users will get stuck with macOS 10.13 for quite some time yet 😢

2021-05-27 07:44 UTC, PetrSvirak commented on DancingGoat/Areas/Admin/Views/SelfConfig/Index.cshtml
> +@{ await Html.RenderPartialAsync("~/Areas/Admin/Views/Shared/_MessagesPartial.cshtml"); }
I believe we introduced the need here, so I would add the commit with the `.yml` to this PR, actually.

2021-05-27 08:00 UTC, PetrSvirak commented on DancingGoat/Areas/Admin/Views/SelfConfig/Index.cshtml
> +@{ await Html.RenderPartialAsync("~/Areas/Admin/Views/Shared/_MessagesPartial.cshtml"); }
Oh my: https://github.com/Kentico/kontent-sample-app-net/pull/126/checks?check_run_id=2682597130

2021-05-27 08:57 UTC, PetrSvirak commented on DancingGoat/Areas/Admin/Views/SelfConfig/Index.cshtml
> +@{ await Html.RenderPartialAsync("~/Areas/Admin/Views/Shared/_MessagesPartial.cshtml"); }
Resolved in https://github.com/Kentico/kontent-sample-app-net/pull/126

2021-05-27 09:32 UTC, jankalfus commented
Closing in favor of https://github.com/Kentico/kontent-sample-app-net/pull/128

2021-05-27 09:32 UTC, closed without merging

2021-05-27 09:47 UTC, PetrSvirak commented on DancingGoat/wwwroot/css/UserMessage.less
> +}
Sorted out in https://github.com/Kentico/kontent-sample-app-net/pull/128

2021-05-27 09:47 UTC, PetrSvirak commented on DancingGoat/wwwroot/css/admin/UserMessage.less
> +  white-space: nowrap; /* added line */
Sorted out in https://github.com/Kentico/kontent-sample-app-net/pull/128