KCL-6857 Move less files into Styles directory, remove css files, add…
Kentico/kontent-sample-app-net pull request #124
Opened 2021-05-26 13:33 UTC by jankalfus

Move less files into Styles directory, remove css files, add compilation for less files

### Motivation

There was no automated compilation for less files before, and the resulting site.css was commited into the repository, which imposed problems (namely, styles from Admin.less were conflicting with the ones in Site.less and broke the Dancing Goat site, whenever they were rebuilt). The issues are fixed and the less files should build automatically.

2021-05-26 13:48 UTC, PetrSvirak requested changes
While the introduction of `npm` is a bit questionable to me, I believe you mentioned that you found no other universal enough way to generate CSS files from LESS (e.g. that would not be tied to a single IDE). 

The change makes sense and not committing the built version of LESS files seems to overweight the cons. But that is just my opinion.

Anyway, the only vice I see is the extra `.gitignore` files

2021-05-26 13:48 UTC, PetrSvirak commented on DancingGoat/Styles/.gitignore
> +*.css.map
I think it should be in the root `.gitignore` (mentioned in https://github.com/Kentico/kontent-sample-app-net/pull/123#discussion_r639457467 already)

2021-05-26 13:48 UTC, PetrSvirak commented on DancingGoat/wwwroot/css/.gitignore
> +﻿*.css
This copy of the file is another reason for me to use the root `.gitignore` O:)

2021-05-27 07:02 UTC, PetrSvirak approved these changes

2021-05-27 07:05 UTC, PetrSvirak requested changes
The `npm ci` still failing during the automated build…

2021-05-27 07:11 UTC, jankalfus commented
Closing in favor of https://github.com/Kentico/kontent-sample-app-net/pull/126

2021-05-27 07:11 UTC, closed without merging